create table if not exists public.sakura_messages (
  id bigint generated by default as identity primary key,
  user_text text not null,
  assistant_text text not null,
  provider text,
  created_at timestamptz not null default now()
);

alter table public.sakura_messages enable row level security;

drop policy if exists "sakura insert messages" on public.sakura_messages;
create policy "sakura insert messages" on public.sakura_messages
  for insert to anon, authenticated with check (true);

drop policy if exists "sakura read messages" on public.sakura_messages;
create policy "sakura read messages" on public.sakura_messages
  for select to anon, authenticated using (true);

create index if not exists sakura_messages_created_at_idx
  on public.sakura_messages (created_at desc);
